import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.string().default("development"),
  PORT: z.coerce.number().default(4000),
  CORS_ORIGIN: z.string().default("http://localhost:5173"),
  APP_URL: z.string().url().default("http://localhost:5173"),

  // Supabase
  SUPABASE_URL: z.string().url(),
  SUPABASE_ANON_KEY: z.string().min(1),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1),

  // Anthropic
  ANTHROPIC_API_KEY: z.string().optional(),
  ANTHROPIC_MODEL: z.string().default("claude-sonnet-4-5"),

  // Resend
  RESEND_API_KEY: z.string().optional(),
  RESEND_FROM_DOMAIN: z.string().default("mail.automoteev.com"),
  RESEND_REPLY_TO_DOMAIN: z.string().default("mail.automoteev.com"),
  RESEND_INBOUND_WEBHOOK_SECRET: z.string().optional(),
  RESEND_EVENTS_WEBHOOK_SECRET: z.string().optional(),

  // Twilio SMS
  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),
  TWILIO_MESSAGING_SERVICE_SID: z.string().optional(),
  TWILIO_FROM_NUMBER: z.string().optional(),

  // Stripe
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_PRICE_MONTHLY: z.string().optional(),
  STRIPE_PRICE_ANNUAL: z.string().optional(),

  // Google
  GOOGLE_MAPS_API_KEY: z.string().optional(),

  // MarketCheck temporary valuation provider
  MARKETCHECK_API_KEY: z.string().optional(),
  MARKETCHECK_PRICE_TIER: z.enum(["base", "premium", "premium_plus"]).default("base"),
  MARKETCHECK_DEALER_TYPE: z.enum(["independent", "franchise"]).default("independent"),

  // EIA
  EIA_API_KEY: z.string().optional(),

  // Web Push (VAPID) — keys generated by `npx web-push generate-vapid-keys`.
  // Public key is also exposed to the frontend as VITE_VAPID_PUBLIC_KEY so the
  // browser can subscribe with it. Subject is the contact for push services
  // to reach you about delivery problems (mailto: address).
  VAPID_PUBLIC_KEY: z.string().optional(),
  VAPID_PRIVATE_KEY: z.string().optional(),
  VAPID_SUBJECT: z.string().default("mailto:gerry@carculus.ai"),

  // Agent
  AUTONOMY_APPROVAL_THRESHOLD: z.coerce.number().int().positive().default(3),

  // Encryption
  PII_ENCRYPTION_KEY: z.string().optional(),
  FIELD_ENCRYPTION_KEY: z.string().optional(), // legacy alias, retained for existing records

  // Legal
  TOS_VERSION: z.string().default("2026-04-24"),
  PRIVACY_VERSION: z.string().default("2026-04-24"),
  AUTONOMY_CONSENT_VERSION: z.string().default("2026-04-24")
});

export const env = envSchema.parse(process.env);
